name: "Setup pnpm"
description: "Install dependencies and setup Node.js environment project with pnpm"

inputs:
  path:
    required: true
    description: "Path to the project directory"

runs:
  using: "composite"
  steps: 
    - uses: pnpm/action-setup@v2
      with:
        version: 7.32.0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: pnpm
        cache-dependency-path: ${{ inputs.path }}/pnpm-lock.yaml
    - name: Install packages
      run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.path }}