name: Build and Deploy

on:
  push:
    branches: 
      - develop
    paths:
      - 'backend/**'
      - 'frontend/**'

  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          tags: sleepergoose/backend:latest
          context: ./backend
          file: ./backend/Dockerfile
          build-args: PROJECT_PORT=5050
          push: true

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/actions/setup-pnpm
        with:
          path: ./frontend
      - name: Build frontend
        run: pnpm build
        working-directory: ./frontend
      - name: Build frontend docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: sleepergoose/frontend:latest

  deploy_images:
    runs-on: ubuntu-latest
    needs:
        - build_backend
        - build_frontend
    steps:
      - name: Print to console
        run: echo Completed
