name: ContinuesIntegration

on:
  workflow_dispatch:          # trigger

jobs:                         # start of the job
  build-backend:              # name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Frontend
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm ci
      - name: Build app
        run: pnpm build
      
