name: ContinuesIntegration

on:
  workflow_dispatch:

jobs:
  analize_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-pnpm
        with:
          path: ./frontend
      - name: Eslint check
        working-directory: ./frontend
        run: pnpm lint
  
  build_frontend:              
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-pnpm
        with:
          path: ./frontend
      - name: Build Angular App
        working-directory: ./frontend
        run: pnpm build

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

